services:
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: qnadb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d qnadb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://pguser:pgpass@db:5432/qnadb
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - HUGGINGFACE_BASE_URL=${HUGGINGFACE_BASE_URL:-https://api-inference.huggingface.co}
      - INTERNAL_API_SECRET=${INTERNAL_API_SECRET:-your-internal-secret-change-in-production}
      - CHAT_MODEL=${CHAT_MODEL:-microsoft/Phi-3.5-mini-instruct}
      - EMBED_MODEL=${EMBED_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BACKEND_URL=http://backend:8000
      - INTERNAL_API_SECRET=${INTERNAL_API_SECRET:-your-internal-secret-change-in-production}
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data: